version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: app-php
    image: nadojba/app-php:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www
    
    networks:
      - app-network
  
  nginx: 
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 9000:80
      - 445:443
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
      


networks:
  app-network:
    driver: bridge